name: Compile SA-MP

on:
  push:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Compile
        run: |
          wget https://github.com/pawn-lang/compiler/releases/download/v3.10.10/pawnc-3.10.10-linux.tar.gz
          tar -xzf pawnc-3.10.10-linux.tar.gz
          chmod +x pawnc-3.10.10-linux/bin/pawncc
          export LD_LIBRARY_PATH=$(pwd)/pawnc-3.10.10-linux/lib

          mkdir -p pawno/include

          wget -q https://github.com/pawn-lang/compiler/archive/refs/heads/master.zip -O compiler.zip
          unzip -q compiler.zip
          cp compiler-master/in
